export const SELECT_ITEM = "SELECT_ITEM";

export const OPEN_POPUP = "OPEN_POPUP";
export const CLOSE_POPUP = "CLOSE_POPUP";

export const OPEN_COMPARE_POPUP = "OPEN_COMPARE_POPUP";
export const CLOSE_COMPARE_POPUP = "CLOSE_COMPARE_POPUP";

export const SET_STEP = "SET_STEP";

export const SET_IS_SIMULATION = "SET_IS_SIMULATION";

export const DATASET_START = "DATASET_START";
export const DATASET_UPLOAD_SUCCESS = "DATASET_UPLOAD_SUCCESS";
export const DATASET_CHECK_URL_SUCCESS = "DATASET_CHECK_URL_SUCCESS";
export const DATASET_SELECT_TABLE_SUCCESS = "DATASET_SELECT_TABLE_SUCCESS";
export const DATASET_FAIL = "DATASET_FAIL";
export const DATASET_REMOVE_UPLOAD = "DATASET_REMOVE_UPLOAD";

export const MODALITY_START = "MODALITY_START";
export const MODALITY_FAIL = "MODALITY_FAIL";
export const MODALITY_SET_LABELS_SUCCESS = "MODALITY_SET_LABELS_SUCCESS";
// export const MODALITY_SET_LABELS = "MODALITY_SET_LABELS";
export const MODALITY_CHANGE_MODE = "MODALITY_CHANGE_MODE";
export const MODALITY_SET_VALIDATION = "MODALITY_SET_LABEL";
export const MODALITY_SET_METRIC = "MODALITY_SET_METRIC";

export const MODEL_START = "MODEL_START";
export const MODEL_GET_MODELS_SUCCESS = "MODEL_GET_MODELS_SUCCESS";
export const MODEL_GET_TRANSFORMS_SUCCESS = "MODEL_GET_TRANSFORMS_SUCCESS";
export const MODEL_FAIL = "MODEL_FAIL";
export const MODEL_SET_MODEL = "MODEL_SET_MODEL";
export const MODEL_SET_TRANSFORMS = "MODEL_SET_TRANSFORMS";
export const MODEL_ADD_TRANSFORM = "MODEL_ADD_TRANSFORM";
export const MODEL_REMOVE_TRANSFORM = "MODEL_REMOVE_TRANSFORM";
export const MODEL_UPLOAD_PIPELINE_SUCCESS = "MODEL_UPLOAD_PIPELINE_SUCCESS";
export const MODEL_REMOVE_PIPELINE = "MODEL_REMOVE_PIPELINE";
export const MODEL_CHANGE_RUN_DB = "MODEL_CHANGE_RUN_DB";
export const MODEL_CHANGE_OPTIMIZER = "MODEL_CHANGE_OPTIMIZER";

export const MODEL_SET_BATCH_SIZE = "MODEL_SET_BATCH_SIZE";
export const MODEL_SET_BATCH_NUMBER = "MODEL_SET_BATCH_NUMBER";

export const BUILDER_SET = "BUILDER_SET";
export const BUILDER_CLEAR = "BUILDER_CLEAR";
export const BUILDER_DEPLOY = "BUILDER_DEPLOY";

